### PR TITLE
Reset counter when duration changed

### LINKED ISSUE #155: When shortening duration and increasing end, while first countup still runs it doesn't work
When shortening duration and increasing end, while first countup still runs
It finishes the new_end countup correctly and then continues the initially interrupted countup that finally reached the first end and stays there

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import CountUp from 'react-countup';

class App extends React.Component {
  state = {
    start: 0,
    end: 1000,
    duration: 10,
  };

  handleOnClick= () => this.setState({
    start: 1000,
    end: 5000,
    duration: 3
  });

  render() {
    return (
      <div>
        <CountUp 
          start={this.state.start}
          end={this.state.end}
          delay={0}
          duration={this.state.duration}
          useEasing={false}
        />
        <button onClick={this.handleOnClick}>Update</button>
      </div>
    );
  }
}

ReactDOM.render(<App />, document.getElementById('root'));
```
To reproduce, click the update button before the initial countup finishes
The sandbox didn't work at all or some reason..

### PR DESCRIPTION
**Pull request by mmarkelov**
Fix #155 
I suppose that we should reset current instance of Counter to fix this kinds of issues

### CODE REVIEW

**Comment by glennreyes** [comment]
@npetridis Can you confirm this works?
@mmarkelov I just added you to the `react-countup` team. Feel free to merge if someone confirmed as I'm a bit busy with other work at the moment.

Thank you!

**Comment by mmarkelov** [comment]
@glennreyes thank you! But it will be nice if you could approve PR before merging it.

**Comment by mmarkelov** [comment]
@glennreyes I just thought about this PR, maybe it is better to clear current instance, before creating new one. I think it would be better than just reset counter

**Comment by glennreyes** [comment]
Why would this be better? Also, if you could add a test that covers this that would be 💯!

**Comment by mmarkelov** [comment]
@glennreyes setting current counter instance to null will not reset it. My mistake. Also add test for this case

**Pull request merged**
