### PR TITLE
Add support for the useIndianSeparators property

### PR DESCRIPTION
**Pull request by bravo-kernel**
This PR adds support for [CountUpOption](https://github.com/inorganik/CountUp.js#usage) property `useIndianSeparators`.

Test with `100000` which should display as `1,00,000`

### CODE REVIEW

**Comment by mmarkelov** [comment]
@bravo-kernel thanks for this one!
I just don't understand why `yarn.lock` file was changed.
I guess both `yarn.lock` and `package-lock` should be excluded from this PR, also could you please add test case?

**Comment by bravo-kernel** [comment]
Apologies for the `yarn.lock` file, totally missed that.

I tried finding a similar test case for the other CountUpOptions but could not find one. Pointer would be appreciated.

**Comment by mmarkelov** [comment]
@bravo-kernel I added the support in #784
Needed to change some other staff, so i'll close your PR, but anyway thank you for your contribution

**Comment by bravo-kernel** [comment]
Awesome! Much appreciated ❤️

**Pull request closed without merging**
